export const SOCIAL_SHARE_INFO = "socialShareInformation"

export const COPY_BLOCK_1 = "copyBlock1"
export const COPY_BLOCK_2 = "copyBlock2"
export const COPY_BLOCK_3 = "copyBlock3"
export const COPY_BLOCK_4 = "copyBlock4"
export const COPY_BLOCK_5 = "copyBlock5"
export const COPY_BLOCK_6 = "copyBlock6"
export const COPY_BLOCK_7 = "copyBlock7"
export const COPY_BLOCK_8 = "copyBlock8"
export const COPY_BLOCK_9 = "copyBlock9"
export const COPY_BLOCK_10 = "copyBlock10"
export const COPY_BLOCK_11 = "copyBlock11"
export const COPY_BLOCK_12 = "copyBlock12"
export const COPY_BLOCK_13 = "copyBlock13"

export const DESCRIPTION_1 = "description1"
export const DESCRIPTION_2 = "description2"
export const DESCRIPTION_3 = "description3"
export const DESCRIPTION_4 = "description4"
export const DESCRIPTION_5 = "description5"
export const DESCRIPTION_6 = "description6"
export const DESCRIPTION_7 = "description7"
export const DESCRIPTION_8 = "description8"

export const TESTIMONIAL_1 = "testimonial1"
export const TESTIMONIAL_2 = "testimonial2"
export const TESTIMONIAL_3 = "testimonial3"
export const TESTIMONIAL_4 = "testimonial4"
export const TESTIMONIAL_5 = "testimonial5"
export const TESTIMONIAL_6 = "testimonial6"
export const TESTIMONIAL_7 = "testimonial7"
export const TESTIMONIAL_8 = "testimonial8"

export const BACKGROUND_IMAGE_1 = "backgroundImage1"
export const BACKGROUND_IMAGE_2 = "backgroundImage2"
export const BACKGROUND_IMAGE_3 = "backgroundImage3"
export const BACKGROUND_IMAGE_4 = "backgroundImage4"

export const CARD_IMAGE_1 = "cardImage1"
export const CARD_IMAGE_2 = "cardImage2"
export const CARD_IMAGE_3 = "cardImage3"
export const CARD_IMAGE_4 = "cardImage4"

export const STANDARD_IMAGE_1 = "standardImage1"
export const STANDARD_IMAGE_2 = "standardImage2"
export const STANDARD_IMAGE_3 = "standardImage3"
export const STANDARD_IMAGE_4 = "standardImage4"

export const HEADINE_LINE_1 = "headline1"
export const HEADINE_LINE_2 = "headline2"
export const HEADINE_LINE_3 = "headline3"
export const HEADINE_LINE_4 = "headline4"
export const HEADINE_LINE_5 = "headline5"
export const HEADINE_LINE_6 = "headline6"

export const STRING_1 = "string1"
export const STRING_2 = "string2"
export const STRING_3 = "string3"
export const STRING_4 = "string4"
export const STRING_5 = "string5"
export const STRING_6 = "string6"
export const STRING_7 = "string7"
export const STRING_8 = "string8"

export const NUMBER_1 = "number1"
export const NUMBER_2 = "number2"
export const NUMBER_3 = "number3"

export const PRICE_CARD_1 = "priceCard1"
export const PRICE_CARD_2 = "priceCard2"
export const PRICE_CARD_3 = "priceCard3"
export const PRICE_CARD_4 = "priceCard4"

// ? New Year Challenge
export const SITE_WIDE_OFFER_SECTION = "siteWideOfferSection"
